spring:
  ai:
    openai:
      api-key: "enter-key-here"
      chat:
        options:
          model: "gpt-3.5-turbo"
          temperature: 0.5

cache-props:
  redis:
    host: redis://localhost:6379
  caffeine:
    expire-after-access-days: 30
    maximum-size: 200
  type: redis
